apiVersion: v1
kind: Service
metadata:
  name: localai-loadbalancer
  labels:
    app: localai
spec:
  selector:
    app: localai
  ports:
    - protocol: TCP
      port: 80              # External port (reachable from outside)
      targetPort: 8080      # The port where LocalAI listens inside the pod
  type: LoadBalancer        # Cloud provider-managed external LoadBalancer