apiVersion: apps/v1
kind: Deployment
metadata:
  name: localai-worker
  labels:
    app: localai-worker
spec:
  replicas: 3  # Number of workers
  selector:
    matchLabels:
      app: localai-worker
  template:
    metadata:
      labels:
        app: localai-worker
    spec:
      resourceClaims:
      - name: mig-devices
        resourceClaimTemplateName: mig-devices
      containers:
      - name: localai-worker
        image: localai/localai:latest-aio-gpu-nvidia-cuda-12
        ports:
        - containerPort: 8000  # Worker port for llama-cpp-RPC
        args: ["worker", "p2p-llama-cpp-rpc"]
        env:
        - name: "TOKEN"
          value: "b3RwOgogIGRodDoKICAgIGludGVydmFsOiAzNjAKICAgIGtleTogVkxSdDdYbmtnU1l1RndLanhsZHBReEQ4djgxNWpoMzhrelZsRnFsWjFBeAogICAgbGVuZ3RoOiA0MwogIGNyeXB0bzoKICAgIGludGVydmFsOiA5MDAwCiAgICBrZXk6IENXRDNTMXBQZHFPN1VubXdFYlU4S3lPd0NQTG52cTRCMFNwOEFkUmtFRVEKICAgIGxlbmd0aDogNDMKcm9vbTogZjBQc05IaHRzeFF6bnpYeUIwamlPMXpJaHpEbG16eHlGUGVMa1l5TExYRApyZW5kZXp2b3VzOiBtcFZlY29GUGJFbm9rdzZXdHJNSkVTZ1ZCUUQxYkMzTlhSMW83cnI0b2xqCm1kbnM6IEFRRjhLSjU4SzFndmRsZEJjTmZPcHdrUWpqYkQ4eXhrSFgzYVk0OXlHRGsKbWF4X21lc3NhZ2Vfc2l6ZTogMjA5NzE1MjAK"
        resources:
          claims:
          - name: mig-devices
            request: mig-1g-10gb
