apiVersion: apps/v1
kind: Deployment
metadata:
  name: localai-worker
  labels:
    app: localai-worker
spec:
  replicas: 3  # Number of workers
  selector:
    matchLabels:
      app: localai-worker
  template:
    metadata:
      labels:
        app: localai-worker
    spec:
      resourceClaims:
      - name: mig-devices
        resourceClaimTemplateName: mig-devices
      containers:
      - name: localai-worker
        image: localai/localai:latest-aio-gpu-nvidia-cuda-12
        ports:
        - containerPort: 8000  # Worker port for llama-cpp-RPC
        args: ["worker", "p2p-llama-cpp-rpc"]
        env:
        - name: "TOKEN"
          value: "REPLACEME"
        resources:
          claims:
          - name: mig-devices
            request: mig-1g-10gb
