apiVersion: apps/v1
kind: Deployment
metadata:
  name: localai-deployment
  namespace: localai
  labels:
    app: localai
spec:
  replicas: 1  # Single instance of the main LocalAI
  selector:
    matchLabels:
      app: localai
  template:
    metadata:
      labels:
        app: localai
    spec:
      resourceClaims:
      - name: mig-devices
        resourceClaimTemplateName: mig-devices
      containers:
      - name: localai
        image: localai/localai:latest-aio-gpu-nvidia-cuda-12
        ports:
        - containerPort: 8080  # HTTP port for API requests
        - containerPort: 9000  # P2P port for worker communication
        args:
        - run
        - --debug
        - --p2p
        - --address
        - 0.0.0.0:8080
        resources:
          claims:
          - name: mig-devices
            request: mig-1g-10gb
